name: Continuous Integration
env:
  DOCKER_IMAGE: wyrihaximusgithubactions/jwage-changelog-generator
  DOCKER_BUILDKIT: 1
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Dockerfile
        uses: docker://hadolint/hadolint:latest-debian
        with:
          entrypoint: hadolint
          args: Dockerfile-build
  build-docker-image:
    name: Build Docker image
    needs:
      - lint-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker version
      - run: docker images
      - name: Install clair-scanner
        run: |
          sudo curl -L https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 -o /usr/local/bin/clair-scanner
          sudo chmod +x /usr/local/bin/clair-scanner
      - run: docker images
      - run: mkdir -p $(echo "./clair/${DOCKER_IMAGE}:${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')
      - run: docker-compose -f .docker/security/docker-compose.yml -p clair-ci up -d
      - run: docker build --no-cache -t "${DOCKER_IMAGE}:${GITHUB_REF##*/}" . -f Dockerfile-build --target=runtime
      - run: docker tag "${DOCKER_IMAGE}:${GITHUB_REF##*/}" "${DOCKER_IMAGE}:sha-${GITHUB_SHA}"
      - run: echo -e "${DOCKER_IMAGE}:${GITHUB_REF##*/}" | xargs -I % sh -c 'clair-scanner --ip 172.17.0.1 -r "./clair/%.json" -l ./clair/clair.log % || (echo "% is vulnerable" && exit 1)'
      - run: docker-compose -f .docker/security/docker-compose.yml -p clair-ci down
      - run: docker images
      - name: Login to Docker Hub
        if: contains(github.ref, 'dependabot') == false
        env:
          DOCKER_USER: ${{ secrets.HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HUB_PASSCODE }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login \
            --username "${{ secrets.DOCKER_USER }}" \
            --password-stdin
      - name: Push branch image to Docker Hub
        if: contains(github.ref, 'dependabot') == false
        run: docker push "${DOCKER_IMAGE}:${GITHUB_REF##*/}"
      - name: Push commit sha image to Docker Hub
        if: contains(github.ref, 'dependabot') == false
        run: docker push "${DOCKER_IMAGE}:sha-${GITHUB_SHA}"